#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : plasma-desktop
Version  : 5.23.90
Release  : 301
URL      : file:///aot/build/clearlinux/packages/plasma-desktop/plasma-desktop-v5.23.90.tar.gz
Source0  : file:///aot/build/clearlinux/packages/plasma-desktop/plasma-desktop-v5.23.90.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : baloo-dev
BuildRequires : boost-dev
BuildRequires : breeze-dev
BuildRequires : breeze-icons
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules
BuildRequires : extra-cmake-modules pkgconfig(glib-2.0)
BuildRequires : extra-cmake-modules pkgconfig(x11-xcb)
BuildRequires : extra-cmake-modules pkgconfig(xcb) xcb-util-cursor-dev xcb-util-image-dev xcb-util-keysyms-dev xcb-util-renderutil-dev xcb-util-wm-dev xcb-util-dev
BuildRequires : extra-cmake-modules-data
BuildRequires : ibus-dev
BuildRequires : kaccounts-integration-dev
BuildRequires : kactivities-dev
BuildRequires : kactivities-stats-dev
BuildRequires : kcompletion-dev
BuildRequires : kcrash-dev
BuildRequires : kded-dev
BuildRequires : kdesignerplugin-dev
BuildRequires : kdoctools
BuildRequires : kdoctools-dev
BuildRequires : kemoticons-dev
BuildRequires : kfilemetadata-dev
BuildRequires : kglobalaccel-dev
BuildRequires : kguiaddons-dev
BuildRequires : ki18n-dev
BuildRequires : kiconthemes-dev
BuildRequires : kinit-dev
BuildRequires : kirigami2-dev
BuildRequires : kitemmodels-dev
BuildRequires : kitemviews-dev
BuildRequires : kjobwidgets-dev
BuildRequires : knewstuff-dev
BuildRequires : knotifyconfig-dev
BuildRequires : kparts-dev
BuildRequires : krunner-dev
BuildRequires : kscreenlocker-dev
BuildRequires : ktextwidgets-dev
BuildRequires : kunitconversion-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : kwin-dev
BuildRequires : kwindowsystem-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXau-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXdamage-dev
BuildRequires : libXdmcp-dev
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXi-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : libevdev-dev
BuildRequires : libinput-dev
BuildRequires : libksysguard-dev
BuildRequires : libxcb-dev
BuildRequires : libxkbfile-dev
BuildRequires : mesa-dev
BuildRequires : phonon-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5Concurrent)
BuildRequires : pkgconfig(Qt5DBus)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5QuickWidgets)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5X11Extras)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(ibus-1.0)
BuildRequires : pkgconfig(x11-xcb)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xkeyboard-config)
BuildRequires : pkgconfig(xorg-evdev)
BuildRequires : pkgconfig(xorg-libinput)
BuildRequires : pkgconfig(xorg-server)
BuildRequires : pkgconfig(xorg-synaptics)
BuildRequires : plasma-framework-dev
BuildRequires : plasma-workspace-dev
BuildRequires : pulseaudio-dev
BuildRequires : qqc2-desktop-style-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtx11extras-dev
BuildRequires : solid-dev
BuildRequires : sonnet-dev
BuildRequires : systemd-dev
BuildRequires : xcb-util-cursor-dev
BuildRequires : xcb-util-dev
BuildRequires : xcb-util-image-dev
BuildRequires : xcb-util-keysyms-dev
BuildRequires : xcb-util-renderutil-dev
BuildRequires : xcb-util-wm-dev
BuildRequires : xcb-util-xrm-dev
BuildRequires : xorg-server-dev

%description
This is new project to replace keyboard (kcmmisc) and kxkb
to manage keyboard hardware configuration and layouts.

%prep
%setup -q -n plasma-desktop
cd %{_builddir}/plasma-desktop

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643426344
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
%cmake .. -DKDE_INSTALL_CONFDIR=/usr/share/xdg
make  %{?_smp_mflags}    V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1643426344
rm -rf %{buildroot}
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
